version: "3"
services:
  client:
    image: "emanewere/multi-client-two"
    mem_limit: 128m
    hostname: client
  server:
    image: "emanewere/multi-server-two"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    image: "emanewere/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
